return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "css",
        "csv",
        "dot",
        "html",
        "javascript",
        "json",
        "julia",
        "latex",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "mermaid",
        "python",
        "r",
        "rnoweb",
        "regex",
        "scss",
        "toml",
        "typescript",
        "typst",
        "vim",
        "vimdoc",
        "yaml",
      },
      highlight = {
        enable = true,
      },
    },
  },
}
